export default [
  {
    id: 1,
    image: "hero-img.svg",
    title: `Mainteny website`,
    text: `Early in January I was part of a small team tasked with rebranding and setting up the homepage for Mainteny. The result was a clean, fully responsive webpage Mainteny could manage via HS.`,
    tags: ["React.js", "HubSpot", "Web development"],
    links: "",
  },
  {
    id: 2,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `React.js`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
  {
    id: 3,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `Test Driven Development`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
  {
    id: 4,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `Back End Development`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
  {
    id: 5,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `Firebase`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
  {
    id: 6,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `Docker`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
]
