export default [
  {
    id: 1,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque inventore quos voluptnihil ipsum, deleniti exercitationem obcaecati ducimus qui nostrum vel voluptatum. Molestias!`,
    tags: ["React.js", "Strapi", "Express.js", "Reedux"],
    links: "",
  },
  {
    id: 2,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `React.js`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
  {
    id: 3,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `Test Driven Development`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
  {
    id: 4,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `Back End Development`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
  {
    id: 5,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `Firebase`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
  {
    id: 6,
    image: "hero-img.svg",
    title: `App for efficiency`,
    text: `Docker`,
    tags: ["React.js", "Strapi"],
    links: "",
  },
]
